[package]
name = "scylla"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "APACHE 2.0"
homepage = "https://docs.iota.org/docs/chronicle/1.1/overview"
repository = "https://github.com/iotaledger/scylla.rs"

[dependencies]
chronicle = { git = "https://github.com/iotaledger/chronicle.rs.git", branch = "framework" }
async-trait = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0",default-features = false, features = ["io-std","fs", "macros", "sync", "net", "io-util", "time", "rt-multi-thread","signal", "full"] }
tokio-tungstenite = "0.13.0"
log = "*"
env_logger = "0.7.1"
futures = "0.3"
futures-util = "0.3.8"

[dev-dependencies]
serde = { version = "1.0.114", features = ["derive"] }
tokio = { version = "1.0", features = ["full", "time", "signal"] }
log = "*"
env_logger = "0.7.1"
futures = "0.3"

[[example]]
name = "scylla"
path = "examples/scylla.rs"
