[package]
name = "scylla-cql"
version = "0.1.0"
authors = ["LK <lk@overdb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
